### ISSUE TITLE
Given a video title as input, generate a video thumbnail

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/sanchay-ai#7]
Develop a thumbnail-via-prompt.sh bash script that does the following:

- Takes a video title as input (you can initialise static data for now)
- Uses generative AI to generate a video thumbnail - 16:9 aspect ratio (or something similar to youtube videos), store the thumbnail in the output directory
- Bonus if you can take a base image as input and generate the video title on top of it

You can choose any generative AI model, but please provide justifications on whichever model you choose.

**Comment by moorjani-ajay** [comment]
I'll take this up! Have fair bit of experience on openCV as well ;)

**Comment by moorjani-ajay** [comment]
Apologies mate, extremely busy at work. Will crack on it when I get a
chance.

Ajay Moorjani
+44 7786297007 | + 91 9867798999


LinkedIn Profile : https://linkedin.com/in/moorjaniajay

**Comment by moorjani-ajay** [comment]
@aadeshkulkarni Although the problem is trivial, I don't think this is currently possible using free resources.

There are no free and reliable APIs that allow txt2img. Self-inferring the open-source models as part of this project will be overkill.

If we have to do that, I am well-versed with ComfyUI, but it will require expensive hardware to run.

Feel free to share your thoughts.
